#!/usr/bin/env python3
"""
`deepwater` bootstrap command.

Creates a local starter folder with a practical guide and example feed configs.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import orjson


START_HERE_TEXT = """# Deepwater: Start Here (2 Minutes)

This folder is designed for agents and humans to get productive immediately.

## Fast Path

1) Pick your data path:

```bash
export DEEPWATER_BASE=./data
```

2) Create feeds from config files:

```bash
deepwater-create-feed --base-path "$DEEPWATER_BASE" --config-dir ./configs
```

3) Inspect available feeds + schema metadata:

```bash
deepwater-feeds --base-path "$DEEPWATER_BASE"
deepwater-feeds --base-path "$DEEPWATER_BASE" --feed trades
```

4) Run the integration example:

```bash
python ./apps/quickstart_app.py
```

5) Check health:

```bash
deepwater-health --base-path "$DEEPWATER_BASE" --check-feeds --max-age-seconds 300
```

6) See usable segment windows (for backtests):

```bash
deepwater-segments --base-path "$DEEPWATER_BASE" --feed trades --status usable --suggest-range
```

7) Compute common contiguous windows across your strategy feed set:

```bash
deepwater-datasets --base-path "$DEEPWATER_BASE" \
  --feeds cb_btcusd,cb_ethusd,cb_solusd,cb_xrpusd,kr_btcusd,kr_ethusd,kr_solusd,kr_xrpusd \
  --json
```

Two-base-path example:

```bash
deepwater-datasets \
  --source A=./data_us \
  --source B=./data_de \
  --feed-ref A:cb_btcusd --feed-ref A:cb_ethusd --feed-ref A:cb_solusd --feed-ref A:cb_xrpusd \
  --feed-ref B:kr_btcusd --feed-ref B:kr_ethusd --feed-ref B:kr_solusd --feed-ref B:kr_xrpusd \
  --json
```

## If You Need a Hard Reset

```bash
deepwater-delete-feed --base-path "$DEEPWATER_BASE" --config-dir ./configs
deepwater-create-feed --base-path "$DEEPWATER_BASE" --config-dir ./configs
```

Next: read `OPS_RUNBOOK.md` for incident procedures and `GUIDE.md` for full details.
"""


GUIDE_TEXT = """# Deepwater Starter Guide

This folder was generated by `deepwater`.

## Folder Layout

- `START_HERE.md`: 2-minute launch checklist
- `OPS_RUNBOOK.md`: copy-paste operational procedures
- `configs/`: feed specs (single files + bundle)
- `apps/`: runnable integration examples

## Feed Configs

Supported formats for `deepwater-create-feed` and `deepwater-delete-feed`:

1) Single feed object.
2) Array of feed objects.
3) Object with `feeds: [...]`.

The required key is `feed_name`.

## Create / Delete Feeds

```bash
# Create all feed specs in this folder
deepwater-create-feed --base-path ./data --config-dir ./configs

# Create from one file
deepwater-create-feed --base-path ./data --config ./configs/trades.json

# Delete by name
deepwater-delete-feed --base-path ./data --feed trades

# Delete using config(s)
deepwater-delete-feed --base-path ./data --config-dir ./configs
```

Create is idempotent. Delete wipes feed files, feed registries, ring shared memory,
and the global registry entry.

## Feed Metadata CLI

Use `deepwater-feeds` when you need to answer:
- what feeds exist?
- what lifecycle settings does a feed have?
- what is the record format (`fmt`) and field layout?

```bash
# list feed names
deepwater-feeds --base-path ./data

# describe one feed
deepwater-feeds --base-path ./data --feed trades

# describe all feeds as JSON (good for tooling/agents)
deepwater-feeds --base-path ./data --all --json
```

## Automatic Segmentation

Segmentation is metadata attached to each feed and managed by writers automatically:
- segment starts on first write (not on `create_feed`)
- segment closes on writer close
- if writer crashes, next writer start closes prior open segment at last level-1 timestamp

Query it with:

```bash
deepwater-segments --base-path ./data --feed trades --status usable --suggest-range
```

## Multi-Feed Dataset Planning

Use `deepwater-datasets` to avoid manual interval intersection when you have many feeds:

```bash
deepwater-datasets --base-path ./data --feeds f1,f2,f3 --json
deepwater-datasets --base-path ./data --feeds f1,f2,f3 --out ./datasets/train_val.json

# multi-source / multi-base-path
deepwater-datasets --source A=./data_a --source B=./data_b --feed-ref A:f1 --feed-ref B:f2 --json
```

It computes contiguous common windows across all provided feeds and suggests
train/validation splits from the longest common window.

## Python Integration Pattern

Use `apps/quickstart_app.py` as your baseline:

1) Open `Platform(base_path)`.
2) Create writer(s) and reader(s) for feed names.
3) Write tuples in feed schema order.
4) Read with `latest()` or `range()`.
5) Close readers/writers/platform.
"""


OPS_RUNBOOK_TEXT = """# Deepwater Ops Runbook

Use this file during incidents and regular operations.

## Required Variable

```bash
export DEEPWATER_BASE=./data
```

## Health Checks

```bash
# Full health signal for monitoring
deepwater-health --base-path "$DEEPWATER_BASE" --check-feeds --max-age-seconds 300
```

Exit codes:
- `0`: healthy
- `1`: unhealthy
- `2`: checker error

## Storage Cleanup

```bash
# Preview
deepwater-cleanup --base-path "$DEEPWATER_BASE" --dry-run

# Execute
deepwater-cleanup --base-path "$DEEPWATER_BASE"
```

## Common Incident Playbooks

### A feed schema is broken during development

```bash
deepwater-delete-feed --base-path "$DEEPWATER_BASE" --feed trades
deepwater-create-feed --base-path "$DEEPWATER_BASE" --config ./configs/trades.json
```

### Multiple feeds need reset from known configs

```bash
deepwater-delete-feed --base-path "$DEEPWATER_BASE" --config-dir ./configs
deepwater-create-feed --base-path "$DEEPWATER_BASE" --config-dir ./configs
```

### Writer appears stuck

1) Run health check command above.
2) Validate process status in your supervisor/systemd.
3) If safe and in dev/test, perform feed reset using commands above.
4) Re-run integration script: `python ./apps/quickstart_app.py`.
"""


QUICKSTART_APP_TEXT = '''#!/usr/bin/env python3
"""
Minimal Deepwater integration app.

Purpose:
- prove end-to-end wiring
- show writer + reader usage
- provide a copyable skeleton for real services
"""
from __future__ import annotations

import os
import time

from deepwater import Platform


def main() -> None:
    base_path = os.environ.get("DEEPWATER_BASE", "./data")
    p = Platform(base_path)

    # This app expects feeds created from ./configs.
    required = ("trades", "quotes")
    missing = [name for name in required if not p.feed_exists(name)]
    if missing:
        names = ", ".join(missing)
        raise RuntimeError(
            f"Missing feed(s): {names}. Run deepwater-create-feed --base-path {base_path} --config-dir ./configs"
        )

    now_us = int(time.time() * 1_000_000)

    tw = p.create_writer("trades")
    tw.write_values(now_us, 100.25, 1.50)
    tw.close()

    qw = p.create_writer("quotes")
    qw.write_values(now_us, 100.20, 100.30)
    qw.close()

    tr = p.create_reader("trades")
    qr = p.create_reader("quotes")

    trades = tr.latest(60)
    quotes = qr.latest(60)

    print(f"base_path={base_path}")
    print(f"trades_records={len(trades)} latest_trade={trades[-1] if trades else None}")
    print(f"quotes_records={len(quotes)} latest_quote={quotes[-1] if quotes else None}")

    tr.close()
    qr.close()
    p.close()


if __name__ == "__main__":
    main()
'''


def _default_trades_spec() -> dict:
    return {
        "feed_name": "trades",
        "mode": "UF",
        "fields": [
            {"name": "ts", "type": "uint64"},
            {"name": "price", "type": "float64"},
            {"name": "size", "type": "float64"},
        ],
        "clock_level": 1,
        "persist": True,
        "chunk_size_mb": 64,
        "retention_hours": 0,
        "index_playback": False,
    }


def _default_quotes_spec() -> dict:
    return {
        "feed_name": "quotes",
        "mode": "UF",
        "fields": [
            {"name": "ts", "type": "uint64"},
            {"name": "bid", "type": "float64"},
            {"name": "ask", "type": "float64"},
        ],
        "clock_level": 1,
        "persist": True,
        "chunk_size_mb": 64,
        "retention_hours": 24,
        "index_playback": False,
    }


def _write_file(path: Path, data: bytes, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"File already exists: {path}")
    path.write_bytes(data)


def create_starter_folder(out_dir: Path, *, force: bool = False) -> Path:
    """
    Create starter folder and files.

    Returns absolute path to the folder.
    """
    out_dir = out_dir.resolve()

    if out_dir.exists() and not out_dir.is_dir():
        raise NotADirectoryError(f"Path exists and is not a directory: {out_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)
    cfg_dir = out_dir / "configs"
    app_dir = out_dir / "apps"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    app_dir.mkdir(parents=True, exist_ok=True)

    _write_file(out_dir / "START_HERE.md", START_HERE_TEXT.encode("utf-8"), force=force)
    _write_file(out_dir / "GUIDE.md", GUIDE_TEXT.encode("utf-8"), force=force)
    _write_file(out_dir / "OPS_RUNBOOK.md", OPS_RUNBOOK_TEXT.encode("utf-8"), force=force)
    _write_file(app_dir / "quickstart_app.py", QUICKSTART_APP_TEXT.encode("utf-8"), force=force)
    _write_file(
        cfg_dir / "trades.json",
        orjson.dumps(_default_trades_spec(), option=orjson.OPT_INDENT_2),
        force=force,
    )
    _write_file(
        cfg_dir / "quotes.json",
        orjson.dumps(_default_quotes_spec(), option=orjson.OPT_INDENT_2),
        force=force,
    )
    _write_file(
        cfg_dir / "feeds.json",
        orjson.dumps(
            {"feeds": [_default_trades_spec(), _default_quotes_spec()]},
            option=orjson.OPT_INDENT_2,
        ),
        force=force,
    )

    return out_dir


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Create a local Deepwater starter folder (guide + feed configs)."
    )
    parser.add_argument(
        "--path",
        default="./deepwater-starter",
        help="Output folder (default: ./deepwater-starter)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite generated files if they already exist",
    )
    parser.add_argument("--quiet", action="store_true", help="Suppress non-error output")
    args = parser.parse_args(argv)

    try:
        created = create_starter_folder(Path(args.path), force=args.force)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    if not args.quiet:
        print(f"Created Deepwater starter folder: {created}")
        print(f"Open first: {created / 'START_HERE.md'}")
        print(f"Ops runbook: {created / 'OPS_RUNBOOK.md'}")
        print(f"Example configs: {created / 'configs'}")
        print(f"App skeletons: {created / 'apps'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
